name: PixStu Tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install diffusers transformers accelerate torch torchvision --extra-index-url https://download.pytorch.org/whl/cpu
          pip install pillow
      - name: Run preset tests
        run: |
          python tools/test_presets.py
      - name: Inpaint import + cache smoke
        run: |
          python - <<'PY'
          from chargen.inpaint import inpaint
          from PIL import Image
          from pathlib import Path
          Path('tmp').mkdir(exist_ok=True)
          # tiny blank images as placeholders
          Image.new('RGB',(32,32),(127,127,127)).save('tmp/init.png')
          Image.new('L',(32,32),255).save('tmp/mask.png')
          # One dry call (will download model in real runs)
          try:
              inpaint('test', 'tmp/init.png', 'tmp/mask.png', steps=4, guidance_scale=2.0, use_cache=True)
          except Exception as e:
              # In CI without weights, import/runtime path still validates
              print('[PixStu] Inpaint smoke encountered (expected in CI without weights):', e)
          PY
