name: QA Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Compile sources
        run: python -m compileall chargen
      - name: Migration sanity check
        run: python tools/check_migration.py
      - name: Run rating aggregator smoke test
        run: python tools/aggregate_ratings.py || true
