name: PixStu UI Smoke
on: { pull_request: { branches: [ main ] }, workflow_dispatch: {} }
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install deps
        run: pip install gradio huggingface_hub pillow
      - name: Run UI Smoke
        run: python tools/test_ui_smoke.py
